### PR TITLE
Get rid of various warnings

### PR DESCRIPTION
**Pull request by cstamas**
In IDE it warns that schema comes from non-HTTPS url. Also, Maven warns about lack of "root", so just add wrapper to please it.

### CODE REVIEW

**Review by gnodet — APPROVED** [review]

**Comment by ppalaga** [comment]
Could we perhaps enable GitHub issues for this project?

**Comment by cstamas** [comment]
Just realized: something was strange (re wrapper, not this project). I used Maven 4.0.0-beta-4 as it is enforced to build this project with that version. Then I did `mvn wrapper:wrapper` that resulting in this PR (+ pom change).

BUT this PR is _wrong_: the default type is script-only, the wrapper.jar should NOT be here!

**Comment by cstamas** [comment]
Is even more strange, as 4.0.0-beta-4 does contain up-to-date wrapper plugin version:
https://github.com/apache/maven/blob/maven-4.0.0-beta-4/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java#L468

So why it did not use "only-script" type that is default in 3.2.0?

**Comment by elharo** [comment]
> Could we perhaps enable GitHub issues for this project?

Probably shouldn't. Most Apache prijects and definitely Maven have been using the Apache Jira instance for a liong time.

**Comment by jorsol** [comment]
> Is even more strange, as 4.0.0-beta-4 does contain up-to-date wrapper plugin version: https://github.com/apache/maven/blob/maven-4.0.0-beta-4/maven-core/src/main/java/org/apache/maven/internal/impl/DefaultLifecycleRegistry.java#L468
> 
> So why it did not use "only-script" type that is default in 3.2.0?

🤔 3.2.0 is not up-to-date, latest version is [3.3.2](https://github.com/apache/maven-wrapper/releases/tag/maven-wrapper-3.3.2), the change to `only-script` type by default was added in 3.3.0:
https://github.com/apache/maven-wrapper/releases/tag/maven-wrapper-3.3.0

**Comment by cstamas** [comment]
@jorsol yup, just realized myself the discrepancy here:
https://gist.github.com/cstamas/c81a66a3f11d90fa9332b893c9ab26b6

(line 9 vs line 10)

**Comment by ppalaga** [comment]
> > Could we perhaps enable GitHub issues for this project?
> 
> Probably shouldn't. Most Apache prijects and definitely Maven have been using the Apache Jira instance for a liong time.

It is true that Maven uses Jira and I'd personally be happier if it wasn't the case. GH issues are faster and much easier to use. I think esp. for subprojects like this one, it is much better to have the issues closer to the code to allow more focused discussions and fine-grained notifications. [mvnd](https://github.com/apache/maven-mvnd/issues) might serve as a positive example. 

Who can enable the issues for this project?

**Pull request merged**
